
[I 150925 12:23:46 web:1908] 200 GET / (106.39.10.162) 6.15ms
[I 150925 12:25:56 web:1908] 200 GET / (106.39.10.162) 13.15ms
[I 150925 12:27:49 web:1908] 200 GET / (106.39.10.162) 18.56ms
[I 150925 12:27:51 web:1908] 304 GET / (106.39.10.162) 10.71ms
[W 150925 12:28:08 control:44] 'active_queues' inspect method failed
[W 150925 12:28:08 control:44] 'registered' inspect method failed
[W 150925 12:28:08 control:44] 'scheduled' inspect method failed
[W 150925 12:28:08 control:44] 'active' inspect method failed
[W 150925 12:28:08 control:44] 'revoked' inspect method failed
[I 150925 12:28:08 web:1908] 200 GET /api/workers?refresh=1 (106.39.10.162) 3124.28ms
[W 150925 12:28:10 control:44] 'active_queues' inspect method failed
[I 150925 12:28:10 web:1908] 200 GET /api/workers?refresh=1 (180.153.206.16) 5133.47ms
[I 150925 12:28:12 web:1908] 200 POST /api/task/async-apply/tasks.subbrute_dispath (203.195.211.242) 18.87ms
[2015-09-25 12:28:12,731: WARNING/Worker-1] /home/ubuntu/mitm/subDomainsBrute/
[I 150925 12:28:16 web:1908] 200 GET / (106.39.10.162) 10.47ms
[I 150925 12:28:18 web:1908] 200 GET /tasks?limit=100 (106.39.10.162) 70.02ms
[I 150925 12:28:29 web:1908] 200 GET /tasks?limit=100&state=SUCCESS (106.39.10.162) 3.25ms
[I 150925 12:29:17 command:85] SIGTERM detected, shutting down

worker: Warm shutdown (MainProcess)
 
 -------------- celery@VM-146-46-ubuntu v3.1.18 (Cipater)
---- **** ----- 
--- * ***  * -- Linux-3.13.0-36-generic-i686-with-Ubuntu-14.04-trusty
-- * - **** --- 
- ** ---------- [config]
- ** ---------- .> app:         __main__:0xb68c5eec
- ** ---------- .> transport:   redis://203.195.211.242:8090/0
- ** ---------- .> results:     disabled
- *** --- * --- .> concurrency: 1 (prefork)
-- ******* ---- 
--- ***** ----- [queues]
 -------------- .> celery           exchange=celery(direct) key=celery
                


worker: Warm shutdown (MainProcess)
[2015-09-25 12:29:20,102: WARNING/MainProcess] Exception
[2015-09-25 12:29:20,103: WARNING/MainProcess] KeyError
[2015-09-25 12:29:20,103: WARNING/MainProcess] :
[2015-09-25 12:29:20,103: WARNING/MainProcess] KeyError(-1219819776,)
[2015-09-25 12:29:20,103: WARNING/MainProcess] in
[2015-09-25 12:29:20,103: WARNING/MainProcess] <module 'threading' from '/usr/lib/python2.7/threading.pyc'>
[2015-09-25 12:29:20,103: WARNING/MainProcess] ignored
[I 150925 12:29:29 command:113] Visit me at http://localhost:9000
[I 150925 12:29:29 command:115] Broker: redis://203.195.211.242:8090/0
[I 150925 12:29:29 command:118] Registered tasks: 
    ['celery.backend_cleanup',
     'celery.chain',
     'celery.chord',
     'celery.chord_unlock',
     'celery.chunks',
     'celery.group',
     'celery.map',
     'celery.starmap',
     'tasks.sqlmap_dispath',
     'tasks.subbrute_dispath']
[I 150925 12:29:29 mixins:225] Connected to redis://203.195.211.242:8090/0
[W 150925 12:29:32 control:44] 'stats' inspect method failed
[W 150925 12:29:32 control:44] 'active_queues' inspect method failed
[W 150925 12:29:32 control:44] 'registered' inspect method failed
[W 150925 12:29:32 control:44] 'scheduled' inspect method failed
[W 150925 12:29:32 control:44] 'active' inspect method failed
[W 150925 12:29:32 control:44] 'reserved' inspect method failed
[W 150925 12:29:32 control:44] 'revoked' inspect method failed
[W 150925 12:29:32 control:44] 'conf' inspect method failed
[2015-09-25 12:29:37,708: WARNING/MainProcess] /usr/local/lib/python2.7/dist-packages/celery/apps/worker.py:161: CDeprecationWarning: 
Starting from version 3.2 Celery will refuse to accept pickle by default.

The pickle serializer is a security concern as it may give attackers
the ability to execute any command.  It's important to secure
your broker from unauthorized access when using pickle, so we think
that enabling pickle should require a deliberate action and not be
the default choice.

If you depend on pickle then you should set a setting to disable this
warning and to be sure that everything will continue working
when you upgrade to Celery 3.2::

    CELERY_ACCEPT_CONTENT = ['pickle', 'json', 'msgpack', 'yaml']

You must only enable the serializers that you will actually use.


  warnings.warn(CDeprecationWarning(W_PICKLE_DEPRECATED))
[2015-09-25 12:29:38,895: WARNING/MainProcess] celery@VM-146-46-ubuntu ready.
[I 150925 12:29:44 web:1908] 200 GET /dashboard (106.39.10.162) 46.29ms
[I 150925 12:29:51 web:1908] 200 POST /api/task/async-apply/tasks.subbrute_dispath (203.195.211.242) 16.21ms
[2015-09-25 12:29:51,871: WARNING/Worker-1] /home/ubuntu/mitm/subDomainsBrute/
[I 150925 12:29:57 web:1908] 200 GET /dashboard (106.39.10.162) 11.55ms
[I 150925 12:29:59 web:1908] 200 GET /tasks?limit=100 (106.39.10.162) 53.42ms
[I 150925 12:30:04 web:1908] 200 GET /task/1a35863c-db18-481c-944d-f1dee87ed93c (106.39.10.162) 57.54ms
[I 150925 12:30:04 web:1908] 200 GET /task/1a35863c-db18-481c-944d-f1dee87ed93c (112.64.235.87) 1.93ms
[I 150925 12:30:21 web:1908] 200 GET /dashboard (106.39.10.162) 12.95ms
[I 150925 12:30:23 web:1908] 304 GET /dashboard (106.39.10.162) 15.23ms
[I 150925 12:38:49 web:1908] 200 GET / (106.39.10.162) 9.93ms
[I 150925 12:38:53 web:1908] 200 GET /tasks?limit=100 (106.39.10.162) 3.33ms
[I 150925 12:39:05 web:1908] 200 GET /tasks?limit=100 (106.39.10.162) 8.20ms
[W 150925 12:39:24 web:1493] 404 GET /worker/celery@VM-146-46-ubuntu (106.39.10.162): Unknown worker 'celery@VM-146-46-ubuntu'
[W 150925 12:39:24 web:1908] 404 GET /worker/celery@VM-146-46-ubuntu (106.39.10.162) 10.56ms
[I 150925 12:39:26 web:1908] 304 GET /monitor (106.39.10.162) 10.69ms
[I 150925 12:39:27 web:1908] 200 GET /monitor/succeeded-tasks?lastquery=1443155966 (106.39.10.162) 0.66ms
[I 150925 12:39:27 web:1908] 200 GET /monitor/completion-time?lastquery=1443155966 (101.226.66.181) 0.63ms
[I 150925 12:39:27 web:1908] 200 GET /monitor/succeeded-tasks?lastquery=1443155966 (180.153.163.186) 0.62ms
[I 150925 12:39:27 web:1908] 200 GET /monitor/broker (106.39.10.162) 14.21ms
[I 150925 12:39:27 web:1908] 200 GET /monitor/failed-tasks?lastquery=1443155966 (106.39.10.162) 1.28ms
[I 150925 12:39:27 web:1908] 200 GET /monitor/completion-time?lastquery=1443155966 (106.39.10.162) 0.71ms
[I 150925 12:39:28 web:1908] 200 GET /monitor/failed-tasks?lastquery=1443155966 (112.64.235.248) 1.61ms
[I 150925 12:40:11 web:1908] 200 POST /api/task/async-apply/tasks.sqlmap_dispath (106.39.10.162) 8.62ms
[I 150925 12:40:11 web:1908] 200 POST /api/task/async-apply/tasks.sqlmap_dispath (106.39.10.162) 8.86ms
[I 150925 12:40:11 web:1908] 200 POST /api/task/async-apply/tasks.sqlmap_dispath (106.39.10.162) 64.01ms
[I 150925 12:40:11 web:1908] 200 POST /api/task/async-apply/tasks.sqlmap_dispath (106.39.10.162) 59.37ms
[I 150925 12:41:04 web:1908] 200 POST /api/task/async-apply/tasks.sqlmap_dispath (106.39.10.162) 8.48ms
[I 150925 12:41:04 web:1908] 200 POST /api/task/async-apply/tasks.sqlmap_dispath (106.39.10.162) 8.45ms
[I 150925 12:41:04 web:1908] 200 POST /api/task/async-apply/tasks.sqlmap_dispath (106.39.10.162) 8.65ms
[I 150925 12:41:04 web:1908] 200 POST /api/task/async-apply/tasks.sqlmap_dispath (106.39.10.162) 10.24ms
[I 150925 12:41:04 web:1908] 200 POST /api/task/async-apply/tasks.sqlmap_dispath (106.39.10.162) 9.14ms
[I 150925 12:41:04 web:1908] 200 POST /api/task/async-apply/tasks.sqlmap_dispath (106.39.10.162) 9.12ms
[I 150925 12:41:04 web:1908] 200 POST /api/task/async-apply/tasks.sqlmap_dispath (106.39.10.162) 8.95ms
[I 150925 12:41:04 web:1908] 200 POST /api/task/async-apply/tasks.sqlmap_dispath (106.39.10.162) 8.80ms
[I 150925 12:41:05 web:1908] 200 POST /api/task/async-apply/tasks.sqlmap_dispath (106.39.10.162) 8.59ms
[I 150925 12:41:05 web:1908] 200 POST /api/task/async-apply/tasks.sqlmap_dispath (106.39.10.162) 8.44ms
[I 150925 12:41:05 web:1908] 200 POST /api/task/async-apply/tasks.sqlmap_dispath (106.39.10.162) 8.41ms
[I 150925 12:41:05 web:1908] 200 POST /api/task/async-apply/tasks.sqlmap_dispath (106.39.10.162) 8.80ms
[I 150925 12:42:18 web:1908] 200 GET /static/js/bootstrap-transition.js?v=871f492dffbee74e6a7134159ac6022b (112.64.235.87) 0.76ms
[I 150925 12:42:18 web:1908] 200 GET /static/js/bootstrap-carousel.js?v=fc8cbc40f39316b8b567b3b96efe9044 (112.64.235.87) 5.67ms
[I 150925 12:42:18 web:1908] 200 GET /static/js/bootstrap-tab.js?v=ca0b95948cc93f4ec18cc3013726a220 (112.64.235.87) 0.71ms
[I 150925 12:42:18 web:1908] 200 GET /static/js/bootstrap-scrollspy.js?v=f7f5435ab136c477b98c1cff0a09c749 (112.64.235.87) 0.66ms
[I 150925 12:42:18 web:1908] 200 GET /static/js/bootstrap-tooltip.js?v=cbba0d4d7ed3f007b8d287f1b5eee7e8 (112.64.235.87) 0.78ms
[I 150925 12:42:18 web:1908] 200 GET /static/js/bootstrap-button.js?v=8b493affaa8e27831d3162d46807b624 (112.64.235.87) 4.81ms
[I 150925 12:42:18 web:1908] 200 GET /static/js/bootstrap-collapse.js?v=e8ddac0b5dd49cfbcf7d3ca8b0098d7b (112.64.235.87) 1.02ms
[I 150925 12:42:18 web:1908] 200 GET /static/js/flower.js?v=c8dc7f7da7155241f49556fe1d5640df (112.64.235.87) 0.68ms
[I 150925 12:42:18 web:1908] 200 GET /static/js/d3.layout.min.js?v=4d73dea16077b0d7d128ecf7a4c20752 (112.64.235.87) 5.55ms
[I 150925 12:42:18 web:1908] 200 GET /static/js/bootstrap-typeahead.js?v=a71319e43efd22bf29161d0e75b892b7 (112.64.235.87) 0.64ms
[I 150925 12:42:18 web:1908] 200 GET /static/js/bootstrap-datetimepicker.min.js?v=8880b6a34ee02b5cb6a75f92b3a7ddc9 (112.64.235.87) 0.72ms
[I 150925 12:42:18 web:1908] 200 GET /static/js/bootstrap-alert.js?v=12586670237d66f7ddc0ba3c6565faff (112.64.235.87) 0.73ms
[I 150925 12:42:18 web:1908] 200 GET /static/js/bootstrap-modal.js?v=5fe4c14f9cbba0a03dfd2cf0a74bb812 (112.64.235.87) 2.40ms
[I 150925 12:42:18 web:1908] 200 GET /static/js/bootstrap-dropdown.js?v=f0a761d953362eb3c150f6ac876a4638 (112.64.235.87) 0.68ms
[I 150925 12:42:18 web:1908] 200 GET /static/js/bootstrap-popover.js?v=69df927a7b524b87ca3badade4fa4e09 (112.64.235.87) 1.00ms
[I 150925 12:42:18 web:1908] 200 GET /static/js/rickshaw.min.js?v=fc927b6dd64118caa563b711bcb2f130 (112.64.235.87) 76.87ms
[I 150925 12:42:18 web:1908] 200 GET /static/js/jquery-ui-1-8-15.min.js?v=88d9f574687d11e3ee3c36b97ac37ffc (112.64.235.87) 144.80ms
[I 150925 12:42:18 web:1908] 200 GET /static/js/d3.min.js?v=eb68d3d1035789d336b285373046b550 (112.64.235.87) 77.41ms
[I 150925 12:42:18 web:1908] 200 GET /static/js/jquery-1.7.2.min.js?v=b8d64d0bc142b3f670cc0611b0aebcae (112.64.235.87) 117.99ms
[W 150925 12:46:22 state:74] Substantial drift from celery@VM-146-46-ubuntu may mean clocks are out of sync.  Current drift is
    932 seconds.  [orig: 2015-09-25 12:30:50.989332 recv: 2015-09-25 12:46:22.318530]
    
[2015-09-25 12:46:22,328: WARNING/Worker-1] /home/ubuntu/mitm/subDomainsBrute/
[I 150925 12:49:04 web:1908] 200 GET /dashboard (106.39.10.162) 10.47ms
[I 150925 12:49:07 web:1908] 200 GET /tasks?limit=100 (106.39.10.162) 8.89ms
[W 150925 13:00:22 web:1908] 404 GET http://sg.search.yahoo.com/ (23.251.41.6) 1.79ms
[I 150925 13:06:34 web:1908] 200 GET / (106.39.10.162) 10.05ms
[I 150925 13:08:25 web:1908] 200 POST /api/task/async-apply/tasks.sqlmap_dispath (106.39.10.162) 8.23ms
[I 150925 13:08:33 web:1908] 200 POST /api/task/async-apply/tasks.sqlmap_dispath (106.39.10.162) 9.75ms
[I 150925 13:08:33 web:1908] 200 POST /api/task/async-apply/tasks.sqlmap_dispath (106.39.10.162) 9.37ms
[I 150925 13:08:49 web:1908] 200 POST /api/task/async-apply/tasks.sqlmap_dispath (106.39.10.162) 8.40ms
[2015-09-25 13:45:43,820: WARNING/Worker-1] {u'data': [], u'success': True, u'error': []}
[2015-09-25 14:17:35,092: WARNING/Worker-1] {u'data': [], u'success': True, u'error': []}
[2015-09-25 14:21:36,997: WARNING/MainProcess] consumer: Connection to broker lost. Trying to re-establish the connection...
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/worker/consumer.py", line 278, in start
    blueprint.start(self)
  File "/usr/local/lib/python2.7/dist-packages/celery/bootsteps.py", line 123, in start
    step.start(parent)
  File "/usr/local/lib/python2.7/dist-packages/celery/worker/consumer.py", line 821, in start
    c.loop(*c.loop_args())
  File "/usr/local/lib/python2.7/dist-packages/celery/worker/loops.py", line 70, in asynloop
    next(loop)
  File "/usr/local/lib/python2.7/dist-packages/kombu/async/hub.py", line 324, in create_loop
    cb(*cbargs)
  File "/usr/local/lib/python2.7/dist-packages/kombu/transport/redis.py", line 957, in on_readable
    self._callbacks[queue](message)
  File "/usr/local/lib/python2.7/dist-packages/kombu/transport/virtual/__init__.py", line 534, in _callback
    self.qos.append(message, message.delivery_tag)
  File "/usr/local/lib/python2.7/dist-packages/kombu/transport/redis.py", line 143, in append
    dumps([message._raw, EX, RK])) \
  File "/usr/lib/python2.7/dist-packages/redis/client.py", line 1821, in execute
    return execute(conn, stack, raise_on_error)
  File "/usr/lib/python2.7/dist-packages/redis/client.py", line 1706, in _execute_transaction
    connection.send_packed_command(all_cmds)
  File "/usr/lib/python2.7/dist-packages/redis/connection.py", line 283, in send_packed_command
    self.connect()
  File "/usr/lib/python2.7/dist-packages/redis/connection.py", line 231, in connect
    raise ConnectionError(self._error_message(e))
ConnectionError: Error 110 connecting 203.195.211.242:8090. Connection timed out.
[I 150925 14:33:25 web:1908] 200 GET / (106.39.10.162) 12.45ms
[I 150925 14:33:30 web:1908] 200 GET /static/js/bootstrap-dropdown.js?v=%3Cimg%3Etsstf0a761d953362eb3c150f6ac876a4638 (106.39.10.162) 0.77ms
[I 150925 14:33:30 web:1908] 200 GET /static/js/bootstrap-modal.js?v=%3Cimg%3Etsst5fe4c14f9cbba0a03dfd2cf0a74bb812 (106.39.10.162) 0.71ms
[I 150925 14:33:30 web:1908] 200 GET /static/js/bootstrap-transition.js?v=%3Cimg%3Etsst871f492dffbee74e6a7134159ac6022b (106.39.10.162) 0.64ms
[I 150925 14:33:30 web:1908] 200 GET /static/js/bootstrap-alert.js?v=%3Cimg%3Etsst12586670237d66f7ddc0ba3c6565faff (106.39.10.162) 0.63ms
[I 150925 14:33:30 web:1908] 200 GET /static/js/jquery-1.7.2.min.js?v=%3Cimg%3Etsstb8d64d0bc142b3f670cc0611b0aebcae (106.39.10.162) 245.14ms
[I 150925 14:33:30 web:1908] 200 GET /static/js/bootstrap-scrollspy.js?v=%3Cimg%3Etsstf7f5435ab136c477b98c1cff0a09c749 (106.39.10.162) 0.84ms
[I 150925 14:33:30 web:1908] 200 GET /static/js/bootstrap-tab.js?v=%3Cimg%3Etsstca0b95948cc93f4ec18cc3013726a220 (106.39.10.162) 0.90ms
[I 150925 14:33:31 web:1908] 200 GET /static/js/bootstrap-tooltip.js?v=%3Cimg%3Etsstcbba0d4d7ed3f007b8d287f1b5eee7e8 (106.39.10.162) 0.94ms
[I 150925 14:33:31 web:1908] 200 GET /static/js/bootstrap-popover.js?v=%3Cimg%3Etsst69df927a7b524b87ca3badade4fa4e09 (106.39.10.162) 0.78ms
[I 150925 14:33:31 web:1908] 304 GET / (106.39.10.162) 10.86ms
[I 150925 14:33:31 web:1908] 200 GET /static/js/bootstrap-button.js?v=%3Cimg%3Etsst8b493affaa8e27831d3162d46807b624 (106.39.10.162) 0.77ms
[I 150925 14:33:31 web:1908] 200 GET /static/js/bootstrap-collapse.js?v=%3Cimg%3Etsste8ddac0b5dd49cfbcf7d3ca8b0098d7b (106.39.10.162) 0.63ms
[I 150925 14:33:31 web:1908] 200 GET /static/js/bootstrap-carousel.js?v=%3Cimg%3Etsstfc8cbc40f39316b8b567b3b96efe9044 (106.39.10.162) 4.81ms
[I 150925 14:33:31 web:1908] 200 GET /static/js/bootstrap-typeahead.js?v=%3Cimg%3Etssta71319e43efd22bf29161d0e75b892b7 (106.39.10.162) 0.86ms
[I 150925 14:33:31 web:1908] 304 GET / (106.39.10.162) 6.57ms
[I 150925 14:33:31 web:1908] 200 GET /static/js/d3.layout.min.js?v=%3Cimg%3Etsst4d73dea16077b0d7d128ecf7a4c20752 (106.39.10.162) 0.69ms
[I 150925 14:33:31 web:1908] 200 GET /static/js/rickshaw.min.js?v=%3Cimg%3Etsstfc927b6dd64118caa563b711bcb2f130 (106.39.10.162) 1.33ms
[I 150925 14:33:31 web:1908] 200 GET /static/js/bootstrap-datetimepicker.min.js?v=%3Cimg%3Etsst8880b6a34ee02b5cb6a75f92b3a7ddc9 (106.39.10.162) 0.66ms
[I 150925 14:33:31 web:1908] 304 GET / (106.39.10.162) 10.48ms
[I 150925 14:33:31 web:1908] 200 GET /static/js/flower.js?v=%3Cimg%3Etsstc8dc7f7da7155241f49556fe1d5640df (106.39.10.162) 0.87ms
[I 150925 14:33:31 web:1908] 200 GET /static/js/d3.min.js?v=%3Cimg%3Etssteb68d3d1035789d336b285373046b550 (106.39.10.162) 464.68ms
[I 150925 14:33:31 web:1908] 304 GET / (106.39.10.162) 13.02ms
[I 150925 14:33:31 web:1908] 304 GET / (106.39.10.162) 10.78ms
[I 150925 14:33:32 web:1908] 200 GET /tasks?limit=100&state=SUCCESS (106.39.10.162) 2.26ms
[I 150925 14:33:32 web:1908] 200 GET /static/js/jquery-ui-1-8-15.min.js?v=%3Cimg%3Etsst88d9f574687d11e3ee3c36b97ac37ffc (106.39.10.162) 1364.97ms
[I 150925 14:33:32 web:1908] 200 GET /static/img/glyphicons-halflings.png (106.39.10.162) 69.40ms
[I 150925 14:33:32 web:1908] 304 GET / (106.39.10.162) 12.02ms
[I 150925 14:33:32 web:1908] 304 GET / (106.39.10.162) 15.46ms
[I 150925 14:33:32 web:1908] 304 GET / (106.39.10.162) 8.57ms
[I 150925 14:33:34 web:1908] 200 GET / (106.39.10.162) 11.24ms
[I 150925 14:33:36 web:1908] 304 GET / (106.39.10.162) 7.89ms
[I 150925 14:33:36 web:1908] 304 GET / (106.39.10.162) 14.97ms
[I 150925 14:33:36 web:1908] 304 GET / (106.39.10.162) 11.95ms
[I 150925 14:33:36 web:1908] 304 GET / (106.39.10.162) 14.29ms
[I 150925 14:33:36 web:1908] 206 GET /static/img/glyphicons-halflings.png (106.39.10.162) 0.76ms
[I 150925 14:33:36 web:1908] 304 GET / (106.39.10.162) 11.28ms
[I 150925 14:33:36 web:1908] 206 GET /static/img/glyphicons-halflings.png (106.39.10.162) 0.82ms
[I 150925 14:33:36 web:1908] 304 GET / (106.39.10.162) 9.52ms
[I 150925 14:33:37 web:1908] 304 GET / (106.39.10.162) 15.18ms
[I 150925 14:33:37 web:1908] 304 GET / (106.39.10.162) 11.29ms
[I 150925 14:33:37 web:1908] 304 GET / (106.39.10.162) 10.70ms
[I 150925 14:33:46 web:1908] 200 GET /tasks?limit=100 (106.39.10.162) 6.88ms
[2015-09-25 14:37:10,200: WARNING/Worker-1] /home/ubuntu/mitm/subDomainsBrute/
[2015-09-25 14:37:10,220: WARNING/Worker-1] /home/ubuntu/mitm/subDomainsBrute/
[I 150925 14:40:10 command:85] SIGTERM detected, shutting down
[2015-09-25 14:54:13,798: WARNING/Worker-1] {u'data': [], u'success': True, u'error': []}
[2015-09-25 15:02:35,939: WARNING/Worker-1] /home/ubuntu/mitm/subDomainsBrute/
[2015-09-25 15:02:35,949: CRITICAL/MainProcess] Couldn't ack u'616c8e1c-08e8-479b-849a-4c3f85f3218f', reason:ConnectionError('Error 111 connecting 203.195.211.242:8090. Connection refused.',)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/kombu/message.py", line 93, in ack_log_error
    self.ack()
  File "/usr/local/lib/python2.7/dist-packages/kombu/message.py", line 88, in ack
    self.channel.basic_ack(self.delivery_tag)
  File "/usr/local/lib/python2.7/dist-packages/kombu/transport/virtual/__init__.py", line 566, in basic_ack
    self.qos.ack(delivery_tag)
  File "/usr/local/lib/python2.7/dist-packages/kombu/transport/redis.py", line 154, in ack
    self._remove_from_indices(delivery_tag).execute()
  File "/usr/lib/python2.7/dist-packages/redis/client.py", line 1821, in execute
    return execute(conn, stack, raise_on_error)
  File "/usr/lib/python2.7/dist-packages/redis/client.py", line 1706, in _execute_transaction
    connection.send_packed_command(all_cmds)
  File "/usr/lib/python2.7/dist-packages/redis/connection.py", line 283, in send_packed_command
    self.connect()
  File "/usr/lib/python2.7/dist-packages/redis/connection.py", line 231, in connect
    raise ConnectionError(self._error_message(e))
ConnectionError: Error 111 connecting 203.195.211.242:8090. Connection refused.
[2015-09-25 15:02:36,132: ERROR/MainProcess] Task tasks.subbrute_dispath[9c05b598-5dfa-49c8-9bd7-77ad74b23a9a] raised unexpected: OSError(2, 'No such file or directory')
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/ubuntu/mitm/tasks.py", line 94, in subbrute_dispath
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory: '/home/ubuntu/mitm/subDomainsBrute/'
[2015-09-25 15:02:36,133: WARNING/Worker-1] /home/ubuntu/mitm/subDomainsBrute/
[2015-09-25 15:02:36,143: CRITICAL/MainProcess] Couldn't ack u'118cb17c-7956-4bfc-b876-29d445f20999', reason:ConnectionError('Error 111 connecting 203.195.211.242:8090. Connection refused.',)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/kombu/message.py", line 93, in ack_log_error
    self.ack()
  File "/usr/local/lib/python2.7/dist-packages/kombu/message.py", line 88, in ack
    self.channel.basic_ack(self.delivery_tag)
  File "/usr/local/lib/python2.7/dist-packages/kombu/transport/virtual/__init__.py", line 566, in basic_ack
    self.qos.ack(delivery_tag)
  File "/usr/local/lib/python2.7/dist-packages/kombu/transport/redis.py", line 154, in ack
    self._remove_from_indices(delivery_tag).execute()
  File "/usr/lib/python2.7/dist-packages/redis/client.py", line 1821, in execute
    return execute(conn, stack, raise_on_error)
  File "/usr/lib/python2.7/dist-packages/redis/client.py", line 1706, in _execute_transaction
    connection.send_packed_command(all_cmds)
  File "/usr/lib/python2.7/dist-packages/redis/connection.py", line 283, in send_packed_command
    self.connect()
  File "/usr/lib/python2.7/dist-packages/redis/connection.py", line 231, in connect
    raise ConnectionError(self._error_message(e))
ConnectionError: Error 111 connecting 203.195.211.242:8090. Connection refused.
[2015-09-25 15:02:36,158: ERROR/MainProcess] Task tasks.subbrute_dispath[9d8ebbc3-c17e-4f61-8cdd-cf7ba165b0f9] raised unexpected: OSError(2, 'No such file or directory')
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/ubuntu/mitm/tasks.py", line 94, in subbrute_dispath
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory: '/home/ubuntu/mitm/subDomainsBrute/'
[2015-09-25 15:02:36,177: CRITICAL/MainProcess] Couldn't ack u'2fb7fadc-8cd4-4808-9646-b35758b192fa', reason:ConnectionError('Error 111 connecting 203.195.211.242:8090. Connection refused.',)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/kombu/message.py", line 93, in ack_log_error
    self.ack()
  File "/usr/local/lib/python2.7/dist-packages/kombu/message.py", line 88, in ack
    self.channel.basic_ack(self.delivery_tag)
  File "/usr/local/lib/python2.7/dist-packages/kombu/transport/virtual/__init__.py", line 566, in basic_ack
    self.qos.ack(delivery_tag)
  File "/usr/local/lib/python2.7/dist-packages/kombu/transport/redis.py", line 154, in ack
    self._remove_from_indices(delivery_tag).execute()
  File "/usr/lib/python2.7/dist-packages/redis/client.py", line 1821, in execute
    return execute(conn, stack, raise_on_error)
  File "/usr/lib/python2.7/dist-packages/redis/client.py", line 1706, in _execute_transaction
    connection.send_packed_command(all_cmds)
  File "/usr/lib/python2.7/dist-packages/redis/connection.py", line 283, in send_packed_command
    self.connect()
  File "/usr/lib/python2.7/dist-packages/redis/connection.py", line 231, in connect
    raise ConnectionError(self._error_message(e))
ConnectionError: Error 111 connecting 203.195.211.242:8090. Connection refused.
[2015-09-25 15:02:36,774: WARNING/MainProcess] consumer: Connection to broker lost. Trying to re-establish the connection...
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/worker/consumer.py", line 278, in start
    blueprint.start(self)
  File "/usr/local/lib/python2.7/dist-packages/celery/bootsteps.py", line 123, in start
    step.start(parent)
  File "/usr/local/lib/python2.7/dist-packages/celery/worker/consumer.py", line 821, in start
    c.loop(*c.loop_args())
  File "/usr/local/lib/python2.7/dist-packages/celery/worker/loops.py", line 70, in asynloop
    next(loop)
  File "/usr/local/lib/python2.7/dist-packages/kombu/async/hub.py", line 267, in create_loop
    tick_callback()
  File "/usr/local/lib/python2.7/dist-packages/kombu/transport/redis.py", line 943, in on_poll_start
    cycle_poll_start()
  File "/usr/local/lib/python2.7/dist-packages/kombu/transport/redis.py", line 302, in on_poll_start
    self._register_LISTEN(channel)
  File "/usr/local/lib/python2.7/dist-packages/kombu/transport/redis.py", line 292, in _register_LISTEN
    self._register(channel, channel.subclient, 'LISTEN')
  File "/usr/local/lib/python2.7/dist-packages/kombu/transport/redis.py", line 268, in _register
    client.connection.connect()
  File "/usr/lib/python2.7/dist-packages/redis/connection.py", line 231, in connect
    raise ConnectionError(self._error_message(e))
ConnectionError: Error 111 connecting 203.195.211.242:8090. Connection refused.
[2015-09-25 15:02:36,776: WARNING/MainProcess] Restoring 3 unacknowledged message(s).
[2015-09-25 15:02:36,834: ERROR/MainProcess] consumer: Cannot connect to redis://203.195.211.242:8090/0: Error 111 connecting 203.195.211.242:8090. Connection refused..
Trying again in 2.00 seconds...

[2015-09-25 15:02:38,844: ERROR/MainProcess] consumer: Cannot connect to redis://203.195.211.242:8090/0: Error 111 connecting 203.195.211.242:8090. Connection refused..
Trying again in 4.00 seconds...

[2015-09-25 15:02:42,857: ERROR/MainProcess] consumer: Cannot connect to redis://203.195.211.242:8090/0: Error 111 connecting 203.195.211.242:8090. Connection refused..
Trying again in 6.00 seconds...

[2015-09-25 15:02:48,871: ERROR/MainProcess] consumer: Cannot connect to redis://203.195.211.242:8090/0: Error 111 connecting 203.195.211.242:8090. Connection refused..
Trying again in 8.00 seconds...

[2015-09-25 15:02:56,886: ERROR/MainProcess] consumer: Cannot connect to redis://203.195.211.242:8090/0: Error 111 connecting 203.195.211.242:8090. Connection refused..
Trying again in 10.00 seconds...

[2015-09-25 15:03:06,903: ERROR/MainProcess] consumer: Cannot connect to redis://203.195.211.242:8090/0: Error 111 connecting 203.195.211.242:8090. Connection refused..
Trying again in 12.00 seconds...

[2015-09-25 15:03:18,923: ERROR/MainProcess] consumer: Cannot connect to redis://203.195.211.242:8090/0: Error 111 connecting 203.195.211.242:8090. Connection refused..
Trying again in 14.00 seconds...

[2015-09-25 15:03:32,942: ERROR/MainProcess] consumer: Cannot connect to redis://203.195.211.242:8090/0: Error 111 connecting 203.195.211.242:8090. Connection refused..
Trying again in 16.00 seconds...

[2015-09-25 15:03:48,965: ERROR/MainProcess] consumer: Cannot connect to redis://203.195.211.242:8090/0: Error 111 connecting 203.195.211.242:8090. Connection refused..
Trying again in 18.00 seconds...

[2015-09-25 15:04:06,988: ERROR/MainProcess] consumer: Cannot connect to redis://203.195.211.242:8090/0: Error 111 connecting 203.195.211.242:8090. Connection refused..
Trying again in 20.00 seconds...

[2015-09-25 15:04:27,011: ERROR/MainProcess] consumer: Cannot connect to redis://203.195.211.242:8090/0: Error 111 connecting 203.195.211.242:8090. Connection refused..
Trying again in 22.00 seconds...

[2015-09-25 15:04:49,042: ERROR/MainProcess] consumer: Cannot connect to redis://203.195.211.242:8090/0: Error 111 connecting 203.195.211.242:8090. Connection refused..
Trying again in 24.00 seconds...

[2015-09-25 15:05:13,072: ERROR/MainProcess] consumer: Cannot connect to redis://203.195.211.242:8090/0: Error 111 connecting 203.195.211.242:8090. Connection refused..
Trying again in 26.00 seconds...

[2015-09-25 15:05:39,104: ERROR/MainProcess] consumer: Cannot connect to redis://203.195.211.242:8090/0: Error 111 connecting 203.195.211.242:8090. Connection refused..
Trying again in 28.00 seconds...

[2015-09-25 15:06:07,137: ERROR/MainProcess] consumer: Cannot connect to redis://203.195.211.242:8090/0: Error 111 connecting 203.195.211.242:8090. Connection refused..
Trying again in 30.00 seconds...

[2015-09-25 15:06:37,169: ERROR/MainProcess] consumer: Cannot connect to redis://203.195.211.242:8090/0: Error 111 connecting 203.195.211.242:8090. Connection refused..
Trying again in 32.00 seconds...

[2015-09-25 15:11:17,334: WARNING/Worker-1] {u'data': [], u'success': True, u'error': []}
[2015-09-25 15:12:20,494: WARNING/Worker-1] {u'data': [], u'success': True, u'error': []}
[2015-09-25 15:16:35,797: WARNING/Worker-1] {u'data': [], u'success': True, u'error': []}
[2015-09-25 15:19:39,650: WARNING/Worker-1] {u'data': [], u'success': True, u'error': []}
[2015-09-25 15:20:51,069: WARNING/Worker-1] {u'data': [], u'success': True, u'error': []}
[2015-09-25 16:20:04,845: WARNING/Worker-1] {u'data': [], u'success': True, u'error': []}
[2015-09-28 04:15:05,584: WARNING/MainProcess] consumer: Connection to broker lost. Trying to re-establish the connection...
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/worker/consumer.py", line 278, in start
    blueprint.start(self)
  File "/usr/local/lib/python2.7/dist-packages/celery/bootsteps.py", line 123, in start
    step.start(parent)
  File "/usr/local/lib/python2.7/dist-packages/celery/worker/consumer.py", line 821, in start
    c.loop(*c.loop_args())
  File "/usr/local/lib/python2.7/dist-packages/celery/worker/loops.py", line 70, in asynloop
    next(loop)
  File "/usr/local/lib/python2.7/dist-packages/kombu/async/hub.py", line 267, in create_loop
    tick_callback()
  File "/usr/local/lib/python2.7/dist-packages/kombu/transport/redis.py", line 943, in on_poll_start
    cycle_poll_start()
  File "/usr/local/lib/python2.7/dist-packages/kombu/transport/redis.py", line 300, in on_poll_start
    self._register_BRPOP(channel)
  File "/usr/local/lib/python2.7/dist-packages/kombu/transport/redis.py", line 283, in _register_BRPOP
    self._register(*ident)
  File "/usr/local/lib/python2.7/dist-packages/kombu/transport/redis.py", line 268, in _register
    client.connection.connect()
  File "/usr/lib/python2.7/dist-packages/redis/connection.py", line 231, in connect
    raise ConnectionError(self._error_message(e))
ConnectionError: Error 110 connecting 203.195.211.242:8090. Connection timed out.
[2015-09-28 18:13:22,397: WARNING/MainProcess] /usr/local/lib/python2.7/dist-packages/celery/apps/worker.py:161: CDeprecationWarning: 
Starting from version 3.2 Celery will refuse to accept pickle by default.

The pickle serializer is a security concern as it may give attackers
the ability to execute any command.  It's important to secure
your broker from unauthorized access when using pickle, so we think
that enabling pickle should require a deliberate action and not be
the default choice.

If you depend on pickle then you should set a setting to disable this
warning and to be sure that everything will continue working
when you upgrade to Celery 3.2::

    CELERY_ACCEPT_CONTENT = ['pickle', 'json', 'msgpack', 'yaml']

You must only enable the serializers that you will actually use.


  warnings.warn(CDeprecationWarning(W_PICKLE_DEPRECATED))
[2015-09-28 18:13:23,651: WARNING/MainProcess] celery@VM-146-46-ubuntu ready.
[I 150928 18:19:08 command:113] Visit me at http://localhost:9010
[I 150928 18:19:08 command:115] Broker: redis://203.195.211.242:8090/0
[I 150928 18:19:08 command:118] Registered tasks: 
    ['celery.backend_cleanup',
     'celery.chain',
     'celery.chord',
     'celery.chord_unlock',
     'celery.chunks',
     'celery.group',
     'celery.map',
     'celery.starmap',
     'tasks.sqlmap_dispath']
[I 150928 18:19:08 mixins:225] Connected to redis://203.195.211.242:8090/0
[I 150928 18:23:40 web:1908] 200 GET / (106.39.10.162) 219.20ms
[I 150928 18:23:40 web:1908] 200 GET / (61.151.218.119) 11.32ms
[I 150928 18:23:41 web:1908] 200 GET /static/css/bootstrap-responsive.css?v=702e8485242b3ae5b4ce75a5ede13acb (106.39.10.162) 19.19ms
[I 150928 18:23:41 web:1908] 200 GET /static/css/rickshaw.min.css?v=48a108292e153ef3cfb53c32283b3d2c (106.39.10.162) 0.72ms
[I 150928 18:23:41 web:1908] 200 GET /static/css/jquery-ui.css?v=11ba5be990454fbbc957fcdf55e339ca (106.39.10.162) 0.77ms
[I 150928 18:23:41 web:1908] 200 GET /static/css/bootstrap-datetimepicker.min.css?v=7468d8a6368bc2a64ad76bce62b9beb2 (106.39.10.162) 0.64ms
[I 150928 18:23:41 web:1908] 200 GET /static/css/flower.css?v=c956fd18aac1e617570f5366d11ad4fd (106.39.10.162) 0.64ms
[I 150928 18:23:41 web:1908] 200 GET /static/css/bootstrap.css?v=7b4cd90ae3b1616f1cf0b93bf5a7769b (106.39.10.162) 743.58ms
